### ISSUE TITLE
[Quest] [The Valiant's Charge] from Marshal Jacob Alerius is missing.

### ISSUE THREAD

**Issue by ClassicMage** [GameFreedomGG/Sindragosa#403] opened 2022-01-16 14:13 UTC
Decription:
NPC Marshal Jacob Alerius [NPC ID: 33225] doesn't provide quest The Valiant's Charge [Quest ID: 13718] to turn 25 Seals you collect from other daily quests givers gating human race from going further Argent Tournament progression.

How it works:
Simple Marshal Jacob Alerius misses a quest The Valiant's Charge after completing its prerequisite Valiant Of Stormwind so you can't turn in Seals and pick another race as human.

How it should work:
Marshal Jacob Alerius should give us a quest to turn 25 Valiant's Seals after completing quest Valiant of Stormwind [Quest ID: 13593], now he doesn't provide that part.

Source (you should point out proofs of your report, please give us some source):
Missing chain part showing us pre-requisite quest: https://wotlk.evowow.com/?quest=13718
NPC providing quests: https://wotlk.evowow.com/?npc=33225
WOWHead comments describing chain progression, especially top comment with point number 5: https://www.wowhead.com/quest=13718/the-valiants-charge#comments

**Comment by Whitemane-Calypso** [comment] 2022-01-17 08:13
https://www.wowhead.com/quest=13718/the-valiants-charge
Just a quick reminder that most of the Ardent Tournament quests/dailies were introduced in 3.2; and will be ingame once their appropriate patch is out.

**Comment by MrTide** [comment] 2022-01-19 12:19
Can confirm i believe quest is missing as well
https://wowwiki-archive.fandom.com/wiki/Quest:Valiant_Of_Stormwind
these quests were added at patch 3.1.0 which we are at right now
all three quests
https://wotlk.evowow.com/?quest=13593

**Comment by UltraNix** [comment] 2022-01-19 20:32
I can't reproduce it. Just rewarded https://wotlk.evowow.com/?quest=13593 and can pick up https://wotlk.evowow.com/?quest=13718

**Comment by ClassicMage** [comment] 2022-01-21 13:58
> I can't reproduce it. Just rewarded https://wotlk.evowow.com/?quest=13593 and can pick up https://wotlk.evowow.com/?quest=13718

Did you try as human? There was same issue on Whitemane (server is part of it's core) and human couldn't pick that, but after swapping race (to gnome) it was possible to obtain. Maybe racial change bugs that, I checked on human with troll racials. I don't have currency to check race change on that server unfortunately.

**Comment by UltraNix** [comment] 2022-01-21 14:17
Yes - as a human.

**Comment by MrTide** [comment] 2022-01-21 21:21
Its most likely stormwind only

**Comment by Game-Freedom** [comment] 2022-01-26 13:51
Bug confirmed - Jacob Alerius SHOULD give this quest along with first dailies.

https://i.imgur.com/U8JuvqM.png

**Closed** 2022-01-28 12:39 UTC
Labels: Priority: Medium, NPC, Quest, Status: Confirmed Bug (Awaiting Development)
