### ISSUE TITLE
[rogues]Vanish+potions --[tmog]Warblade of the Hakkari(offhand) 

### ISSUE THREAD

**Issue by Pisswine** [GameFreedomGG/Sindragosa#515] opened 2022-02-16 12:51 UTC
Hi, 
1-[rogue]Vanish+ potions :due to my in queries apparently in blizzard and experience with other private servers, the rogue spell "Vanish" should -/+ Combat momentarily in Boss fights. Even in later expansions which blizzard had limited this, you could do it at least once. So you'd prepot, use a pot during boss fight and Vanish and use another one but RN it apparent should be doable infinitely.that's why dpsing with mutilate rogues would be very expensive currently. The steps to reproduce this is to engage any boss in any raid, use a Potion, Vanish, and you'll see that you can't use another potion after the cd.

2-[tmog] Warblade of the Hakkari (offhand).

https://wowwiki-archive.fandom.com/wiki/Warblade_of_the_Hakkari_(off-hand)

This item does not show up as a tmogable item for either main hand or offhand. The main hand version of this sword works but the offhand doesn't show up. The steps to reproduce this is to get the item, talk to the transmog NPC in dalaran but you won't see the item in the list although it meets every requirement for the character.

I hope this is helpful. Cheers.

**Comment by Soufly** [comment] 2022-02-16 12:56
U cant get out of combat if u pull a raid boss... That was fixed at the end of tbc.

**Comment by Pisswine** [comment] 2022-02-16 13:04
> U cant get out of combat if u pull a raid boss... That was fixed at the end of tbc.

Well i have talked to some people and checked out expansion changelogs. The results are not 100% clear but the consensus on the "blizzlike" scripting seems to be that it doesn't remove combat rather instantly -/+ combat to reset stuff. The change you're referring to seems to be implemented in Cataclysm.

**Comment by Soufly** [comment] 2022-02-16 13:20
It was implemented with feign death/shadowmeld/vanish to prevent ppl eating/swapping items/ressing ppl out of combat.

**Comment by Soufly** [comment] 2022-02-16 13:22
Bc icon.gif Patch 2.3.0 (13-Nov-2007): Fixed a bug in which Hunters were able to disengage from combat using Feign Death during boss encounters.

**Comment by Soufly** [comment] 2022-02-16 13:26
Note that these abilities no longer remove you from combat during Boss Fights (only at the end of wipes if you time it correctly). https://wowpedia.fandom.com/wiki/Combat

**Comment by Renoucer** [comment] 2022-02-16 17:35
Vanish works only when you are the last one standing alive,

**Comment by Pisswine** [comment] 2022-02-17 10:08
> Note that these abilities no longer remove you from combat during Boss Fights (only at the end of wipes if you time it correctly). https://wowpedia.fandom.com/wiki/Combat

I absolutely understand that it shouldn't end combat. I should also mention that my source for this is a few videos of Retail floating around and Changelogs on sites like wowwiki. These of course aren't the most reliable sources but in the sprit of "blizzlike" scripting, it might be worth looking into it. The change you're referring to seems to be implemented in 3.0.9 patch.
 It doesn't let you remove combat with anything in an ongoing boss fight may it be FD or shadowmeld or Vanish and etc. But apparently rogues still got reset on potions. In fact there's another unofficial changelog on early patches in Cataclysm in which they've specifically changed it for rogues but even then, they can do it once. So while other classes prepot and use a potion during the encounter, they use one more after one Vanish. After that, Vanish doesn't reset anything.
It apparently is about how Vanish specifically interacts with a mechanic called combat echo or aggro echo or something Which unfortunately I don't remember or find the archived discussions about it atm. Keep in mind that it's well documented that you still should not be able to swap gear or eat good and stuff. It only interacts with the potion cd.

**Comment by Soufly** [comment] 2022-02-17 10:54
https://media4.giphy.com/media/yvBAuESRTsETqNFlEl/200w.webp?cid=ecf05e47l7rshtkhjjomx2xr88pnfl4euvgib3baf5bxxte8&rid=200w.webp&ct=g

**Comment by Soufly** [comment] 2022-02-17 10:55
![ryan-reynolds-facepalm-gif](https://user-images.githubusercontent.com/36957911/154463984-f2edc224-888c-4ba4-bdec-37379677f670.gif)

**Comment by Godmatik** [comment] 2022-02-17 17:15
Just close this please ... not a bug

**Closed** 2022-02-18 09:25 UTC
