### ISSUE TITLE
Vezax10 Normal, Saronite pool stacks giving no mana.

### ISSUE THREAD

**Issue by DrunkenLeto** [GameFreedomGG/Sindragosa#448] opened 2022-01-24 23:02 UTC
Decription: Saronite in Vezax 10 man Normal, gives "zero" mana in return, doesn't matter how many ticks you get.

How it works: Me (Disc Priest), and our holy paladin got the stacks, and have no mana in return. I usually got into the pool with shield on, just to negate damage, seeing that there is no incoming mana, I removed all my protective buffs, including Divine Aegis, and PW: Shield. Got Damage, got stacks, no mana gained.

How it should work: Normally the Vezax saronite green pools should give you a stacking saronite debuff which damages and gives mana to the person who stands inside. 

Source (you should point out proofs of your report, please give us some source):
![WoWScrnShot_012522_020055](https://user-images.githubusercontent.com/98362111/150879405-8fa29de1-20cc-4a39-8f7b-c66bbefbaf46.jpg)
![WoWScrnShot_012522_020036](https://user-images.githubusercontent.com/98362111/150879409-c987c4ef-c767-41d5-b855-654f721eb744.jpg)
![unknown (1)](https://user-images.githubusercontent.com/98362111/150879412-3488c387-3b06-4eea-927a-e2659d4bc725.png)
![unknown](https://user-images.githubusercontent.com/98362111/150879413-d72253c9-92c4-4b2e-b520-8c6761e2b71e.png)

**Comment by MrTide** [comment] 2022-01-25 21:56
I did reset all of the characters that had this issue (.unaura all) waiting for their next week raid to see if they still have the same issue. i can't reproduce this

**Comment by Godmatik** [comment] 2022-01-25 22:47
We did vezax 10m a couple days ago, didn't have any issues with mana from the pools

If you have an absorb on you such as a priest shield you won't get mana because the amount of mana you gain is equal to amount of damage you take.

**Comment by danniellos94** [comment] 2022-01-25 23:21
Just did vezax 25m normal and no healer had problem with mana too.

**Comment by Game-Freedom** [comment] 2022-01-26 16:13
It worked correctly when I've tested it. Closing.

**Closed by Game-Freedom** 2022-01-26 16:13 UTC
Labels: Raid, Priority: Low, NPC, Spell, Status: Closed- Not a Bug
