### ISSUE TITLE
Warrior crit bug

### ISSUE THREAD

**Issue by Sruczczi** [GameFreedomGG/Sindragosa#330] opened 2021-12-15 16:21 UTC
Decription:Warrior crit chance

How it works:When i use berseker stance i have +3% crit then when i switch stance i have -6% crit. It back to normal after relog, but if i will use berseker stance again it get bug again.

How it should work: It should +3%crit on berseker stance and back to normal in other stance, not -6% :D

Source (you should point out proofs of your report, please give us some source): Just create warrior and change stance to berserker then back to arms or prot

**Comment by zalger** [comment] 2021-12-16 21:53
Not true. https://www.youtube.com/watch?v=e68G22zccyM

**Comment by Sruczczi** [comment] 2021-12-16 22:51
https://user-images.githubusercontent.com/96195775/146460564-f206ca24-ce26-4e49-a554-97548ec4371f.mp4

**Comment by Sruczczi** [comment] 2021-12-18 21:00
Up. Help me please

**Comment by Loken-Whitemane** [comment] 2022-01-04 23:49
Duplicate of https://github.com/GameFreedomGG/Sindragosa/issues/338

**Closed by Loken-Whitemane** 2022-01-04 23:49 UTC
Labels: Status: Duplicate, Class: Warrior
