### ISSUE TITLE
Unable to whisper

### ISSUE THREAD

**Issue by Aiteri** [GameFreedomGG/Sindragosa#266] opened 2021-11-29 13:58 UTC
Decription: on a single account for an unknown i can't whisper at all, while other chat functions work fine. I get no messages or anything, sending whisper does nothing, while I can be whispered to. On another accounts there is no such problem - can whisper easily. I have tried deleting cache, wtf, interface folders, disabling addons and removing them entirely, /resetchat - nothing worked for me. Sent a ticket to gm - here's a response: https://i.imgur.com/jzeKaKN.png So I am creating a bug report.

How it works: I simply can't whisper. Sending a message does nothing.

How it should work:

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment] 2021-12-03 16:13
Hello
Solved ingame you should be fine now
Sorry for inconvenience
Can be closed

**Comment by Loken-Whitemane** [comment] 2022-01-04 22:42
Not a bug, resolved via GM Ticket. Closing this out.

**Closed by Loken-Whitemane** 2022-01-04 22:42 UTC
Labels: Closed: No Resolution
